### ISSUE TITLE
Windows wheels missing in 1.0.3

### ISSUE THREAD

**Issue by letmaik** [Unidata/cftime#100]
1.0.3 is lacking Windows wheels. Releasing a new patch version without releasing the wheels at the same time means that anyone trying to pip install it on Windows without specifying an exact version now sees [failures](https://github.com/GIS4WRF/gis4wrf/issues/105#issuecomment-444032903). 1.0.2.1 has Windows wheels, and 1.0.3 as a patch release should be fully compatible to the old version, but this is not the case if the wheels are missing. This is especially annoying since cftime is often pulled in as transitive dependency, e.g. from the netCDF4 package. So pinning netCDF4 to a fixed version alone doesn't help, I would also have to pin the cftime version to 1.0.2.1 in that case to prevent any possible issues.

The point of this issue is to highlight the problem of release timelines. It's not enough to upload binary wheels days or weeks after the source package was released to PyPI. Ideally it should be an atomic operation where a new version immediately comes with all the wheels.

**Comment by jswhit** [comment]
Fixed.  We're working on an automated build system for macos,linux and windows wheels (https://github.com/MacPython/cftime-wheels), but help is welcome.
