### ISSUE TITLE
Datetime comparison

### ISSUE THREAD

**Issue by jswhit** [Unidata/cftime#11]
copy of https://github.com/Unidata/netcdf4-python/issues/639

When a netcdftime datetime object is unable to be compared to another object, the __richcmp__ method raises a TypeError. In previous versions of the module the method would return NotImplemented, causing the appropriate method on the other object to be called and allowing classes to be written which could be compared against netcdftime datetime objects. With the TypeError behaviour this is no longer the case.

Can the previous behaviour be restored?

**Comment by jswhit** [comment]
Seems like simply changing TypeError to NotImplementedError in __richcmp__ would fix this.  Are they any downsides to this?

**Comment by shoyer** [comment]
CC @djkirkham

> Seems like simply changing TypeError to NotImplementedError in richcmp would fix this. Are they any downsides to this?

It needs to be `return NotImplemented` to properly defer to the implemention on the other object, not `raise NotImplementedError`

**Comment by pdearnshaw** [comment]
This problem has arisen in a project I am working on so I thought to try this and got unexpected results, basically `cftime.datetime` objects become comparable to anything! ie. breaks `not_comparable_4` test in `test_richcmp`.

Is there anything else that can be done?
