### ISSUE TITLE
Time deltas giving incorrect results

### ISSUE THREAD

**Issue by nhsavage** [Unidata/cftime#115]
I am getting some odd results when doing date differences with cftime for a times of 1 hour. Given that cftime stores times natively as days, seconds and microseconds, I would not expect this to be because of rounding errors. 

```

>>> date1=cftime.Datetime360Day(2010, 1, 30, 0)
>>> date2=cftime.Datetime360Day(2010, 1, 30, 1)
>>> date1
cftime._cftime.Datetime360Day(2010, 1, 30, 0, 0, 0, 0, -1, 1)
>>> date2
cftime._cftime.Datetime360Day(2010, 1, 30, 1, 0, 0, 0, -1, 1)
>>> delta = date2 - date1
>>> delta
datetime.timedelta(0, 3599, 999985)
>>> print(delta)
0:59:59.999985

you don't get this with datetime dates:
>>> date1=datetime.datetime(2010, 1, 30, 0)
>>> date2=datetime.datetime(2010, 1, 30, 1)
>>> delta = date2 - date1
>>> delta
datetime.timedelta(0, 3600)
>>> print(delta)
1:00:00

>>> cftime.__version__
'1.0.0b1'


```

**Comment by jswhit** [comment]
With 1.0.3.4 I get `1:00:00`.  Please update and let us know if the problem persists for you.

**Comment by nhsavage** [comment]
I also  get this  on my home PC when I update to 1.0.34 (I didn't with 1.0.1 which is what I initially had.I think that this can be closed.
