### ISSUE TITLE
_parse_date does not report microseconds

### ISSUE THREAD

**Issue by davidhassell** [Unidata/cftime#121]
Hello,

`cftime._parse_date` does not return microseconds:

```
In [17]: import cftime

In [18]: cftime.__version__
Out[18]: '1.0.3.4'

In [19]: cftime._parse_date('2000-12-1 12:23:45')
Out[19]: (2000, 12, 1, 12, 23, 45, 0)

In [20]: cftime._parse_date('2000-12-1 12:23:45.123456')
Out[20]: (2000, 12, 1, 12, 23, 45, 0)
```

I see in the code (https://github.com/Unidata/cftime/blob/master/cftime/_cftime.pyx#L934) that this has been thought about before.

Is there a reason why this is so? Could they be returned, either as an extra returned argument, or as seconds represented by a `float`?

Many thanks,
David

**Comment by jswhit** [comment]
I honestly don't remember.  Perhaps the reason is that the date calculation algorithm doesn't have microsecond accuracy (more like 100 microseconds) - so we though allowing microseconds in the reference date and units string would be dangerous.   Don't see why it can't be enabled though - with a caveat.

**Comment by davidhassell** [comment]
OK, thanks. I have prepared a pull request that returns the microseconds component from `cftime._parse_date`

```
>>> cftime._parse_date('2000-01-02 12:23:34')
(2000, 1, 2, 12, 23, 34, 0, 0)
>>> cftime._parse_date('2000-01-02 12:23:34.56')
2000, 1, 2, 12, 23, 34, 560000, 0)
```

Nothing (yet) in the code uses these returned microseconds. However, I would like to use them in the PR mentioned in  https://github.com/Unidata/cftime/issues/118#issuecomment-534680969 - which would allow a `datetime` object (or child thereof) to be initializable from a datetime string.

**Comment by jswhit** [comment]
PR merged.
