### ISSUE TITLE
Time for a release

### ISSUE THREAD

**Issue by jhamman** [Unidata/cftime#123]
I'm just noticing that its been >11 months since cftime had a release. Since then a number of changes have landed. @jswhit - how do you feel about issuing a release round about now?

**Comment by jswhit2** [comment]
I'll try to get one out this weekend.

**Comment by jswhit** [comment]
It would be nice to have python 3.8 wheels with this release, but the 3.8 builds are failing 

https://github.com/MacPython/cftime-wheels/issues/2

**Comment by jswhit** [comment]
release done, includes 3.8 wheels.

**Comment by matthew-brett** [comment]
Excellent - thanks for doing that.
