### ISSUE TITLE
date2num error when converting a DatetimeProlepticGregorian object in cftime 1.0.4

### ISSUE THREAD

**Issue by spencerkclark** [Unidata/cftime#126]
In version 1.0.3.4 of cftime the following succeeds without an error:
```
In [1]: import cftime

In [2]: d = cftime.DatetimeProlepticGregorian(1, 1, 1)

In [3]: cftime.date2num(d, 'days since 0001-01-01', 'proleptic_gregorian')
Out[3]: 0.0
```
However, with 1.0.4, the following occurs:
```
In [3]: cftime.date2num(d, 'days since 0001-01-01', 'proleptic_gregorian')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-5b0bfcafe058> in <module>
----> 1 cftime.date2num(d, 'days since 0001-01-01', 'proleptic_gregorian')

cftime/_cftime.pyx in cftime._cftime.date2num()

AttributeError: 'cftime._cftime.DatetimeProlepticGregorian' object has no attribute 'tzinfo'
```
We came across this in the xarray test suite, xref: https://github.com/pydata/xarray/issues/3427.  Was this an intentional change?

**Comment by jswhit** [comment]
Seems to be related to 

https://github.com/Unidata/cftime/pull/110

@barronh, could you take a look?

**Comment by jswhit** [comment]
Looks like a simple fix for a typo that slipped through in PR #110 (PR #127).  Assuming the xarray test suite runs cleanly with this fix, I'll push a 1.0.4.1 release.

**Comment by barronh** [comment]
I’m at a conference thru tomorrow, so I haven’t been able to look at it. I trust that you’re right. I could look on Thursday.

**Comment by jswhit** [comment]
Will go ahead and merge since the fix is trivial.

**Comment by jswhit** [comment]
F
