### ISSUE TITLE
Improved exception messages for time differences

### ISSUE THREAD

**Issue by nocollier** [Unidata/cftime#128]
version: 15aab33e18ab705217fafbe84e7f7beb2c405a87
environment: Linux/OSX python3

The exception messages here:

https://github.com/Unidata/cftime/blob/master/cftime/_cftime.pyx#L1363

inform the user that they cannot compute time differences with different calendars. However, this exception is also thrown if the user tries to convert across the beginning of a calendar. For example:

```
d1 = cf.num2date(0,"days since 1500-01-01 00:00:00",calendar="standard")
d2 = cf.num2date(0,"days since 1600-01-01 00:00:00",calendar="standard")
print(d2-d1)
```

throws `cannot compute the time difference between dates with different calendars` which is misleading. I think that the issue here is that the conversion happens across 1582-10-4 and so perhaps internally the calendar of `d1` is changed and therefore different by the time the difference is computed. 

Could I suggest an expanded exception message which would inform the user as to what is going on? Perhaps adding ' or subtraction occurs across the valid range of the given calendar'? At least this would direct the user to look up information about the calendar they are using.

**Comment by jswhit** [comment]
It works if you specify `only_use_cftime_datetimes=True`

```python
>>> import cftime as cf
>>> d1 = cf.num2date(0,"days since 1500-01-01 00:00:00",calendar="standard")
>>> d2 = cf.num2date(0,"days since 1600-01-01 00:00:00",calendar="standard",\
        only_use_cftime_datetimes=True)
>>> print(d2-d1)
36515 days, 0:00:00
~
```

The issue is that by default num2date converts the datetime instances to python native datetime objects after the transition between Julian and Gregorian, and uses the python datetime arithmetic (which is more accurate than the algorithms used by cftime internally).  I'm not sure right now how we can catch this specific error and issue a more informative message, but I'll think about it some more.

**Comment by jswhit** [comment]
With PR #131 the error message reads

```
Traceback (most recent call last):
  File "cftime_issue128.py", line 14, in <module>
    print(d2-d1)
  File "cftime/_cftime.pyx", line 1392, in cftime._cftime.datetime.__sub__
    Return indices of a netCDF time variable corresponding to the given times.
ValueError:
cannot compute the time difference between dates with different calendars.
One of the datetime objects may have been converted to a native python
datetime instanace.  Try using only_use_cftime_datetimes=True when creating the
datetime object
```

**Comment by nocollier** [comment]
Thanks a lot, wasn't aware of that option.
