### ISSUE TITLE
Enable intersphinx links

### ISSUE THREAD

**Issue by keewis** [Unidata/cftime#132]
At the moment, the documentation of `cftime` provides a intersphinx file (https://unidata.github.io/cftime/objects.inv), but it does not contain entries for `cftime.datetime` and other attributes of the module:
```bash
$ python -m sphinx.ext.intersphinx https://unidata.github.io/cftime/objects.inv
std:doc
	api                                      API                                     : api.html
	index                                    cftime                                  : index.html
	installing                               Installation                            : installing.html
std:label
	genindex                                 Index                                   : genindex.html
	modindex                                 Module Index                            : py-modindex.html
	search                                   Search Page                             : search.html
```
This causes broken links and sphinx warnings in projects that try to link to it (e.g. [xarray](https://github.com/pydata/xarray/pull/3516)).

The easiest way I know to fix this would be to remove `:noindex:` from `docs/api.rst`.

**Comment by jswhit** [comment]
Pull request would be very much appreciated
