### ISSUE TITLE
Add support for daysinmonth

### ISSUE THREAD

**Issue by huard** [Unidata/cftime#137]
It would be useful to have a `daysinmonth` accessor such as with standard pandas datetime indexes.

**Comment by spencerkclark** [comment]
Agreed; I've found myself needing something like this many times. It would also greatly simplify [one of the examples in xarray's docs](http://xarray.pydata.org/en/stable/examples/monthly-means.html#a-few-calendar-functions-to-determine-the-number-of-days-in-each-month).

**Comment by jswhit** [comment]
Closed by PR #138
