### ISSUE TITLE
pyproject.toml missing in 1.1.1.1 source on PyPI

### ISSUE THREAD

**Issue by neishm** [Unidata/cftime#154]
Unfortunately the `pyproject.toml` file is absent from the just-uploaded source tarball.  This may cause failures with `pip install` when numpy or cython are not yet installed, and there is no pre-built binary wheel available on the platform.

This file does appear when I run `python setup.py sdist` locally on the `1.1.1.1rel` tag, so there's no problem with the repository itself.  Just a weird glitch in the build machine maybe?

**Comment by ocefpaf** [comment]
We need to add it to the manifest.in I'll send a PR to fix that and add some tarball checks to avoid future regressions.

**Comment by jswhit** [comment]
https://github.com/pypa/setuptools/issues/1632

**Comment by jswhit** [comment]
Fixed with 1.1.1.2 release.
