### ISSUE TITLE
pandas 1.0.3 does not recognize cftime.DatetimeGregorian as time

### ISSUE THREAD

**Issue by fmaussion** [Unidata/cftime#155]
Apologies if I've missed this issue being raised elsewhere. 

Creating a pandas index from `cftime.DatetimeGregorian` objects results in an index which is not understood as a time index by pandas. I think this appeared with the latest pandas version but I'm not sure:

```python
import cftime
import pandas as pd

print(cftime.__version__)
print(pd.__version__)

t = [cftime.DatetimeGregorian(2012, 6, 1)]
s = pd.Series([1], index=t)

s.index.year
``` 

Output:

```
1.1.1.1
1.0.3
Traceback (most recent call last):
  File "/home/mowglie/Documents/git/salem/salem/sandbox.py", line 10, in <module>
    s.index.year
AttributeError: 'Index' object has no attribute 'year'
```

Thanks!

**Comment by spencerkclark** [comment]
I'd be surprised if this particular example ever worked.  Pandas on its own does not know how to cast cftime dates to an `xarray.CFTimeIndex`.  

Perhaps you were hit by the change made in https://github.com/Unidata/cftime/pull/135, where `datetime.datetime` objects were no longer returned by default when possible by `cftime.num2date`?

**Comment by fmaussion** [comment]
Thanks for the quick reply!

This seems to be it. I'm using `netCDF4.num2date` to read times that I feed to pandas afterwards. Strangely enough, latest netCDF4.num2date on my env (4.8.3) does not have the `only_use_cftime_datetimes` kwarg available yet (although it is [documented](https://unidata.github.io/netcdf4-python/netCDF4/index.html#netCDF4.num2date)). 

Anyways, I'll find my way possibly by using cftime.num2date directly. I'm a it concerned that  cftime.num2date now returns objects that aren't recognized by pandas, but I think you guys know what you have to do ;-)
