### ISSUE TITLE
Error in date2num when called with 0-dimensional numpy array

### ISSUE THREAD

**Issue by neishm** [Unidata/cftime#185]
In the latest version (1.2.0), the `date2num` routine is raising an AttributeError when called with a degenerate (0-dimensional) numpy array.  The following is a minimal example for triggering the exception:

```python
from cftime import date2num
from datetime import datetime
import numpy as np
dates = np.array(datetime(2010, 2, 2, 0, 0))
print (date2num(dates, units="hours since 2010-02-01 00:00:00"))
```
This gives the following stack trace (with Python 3.6.9 on Ubuntu 18.04):
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "cftime/_cftime.pyx", line 231, in cftime._cftime.date2num
AttributeError: 'numpy.ndarray' object has no attribute 'year'
```
This used to work on previous versions of cftime.  Looking through _cftime.pyx, it appears maybe there's a glitch in how the "isscalar" flag is determined.  From what I understand, the code tries to invoke `dates[0]`, then when it errors out it considers "dates" to be a scalar, then wraps it in a numpy array.  In my case that causes it to have a (degenerate) numpy array nested inside a one-dimensional numpy array.

**Comment by jswhit** [comment]
Thanks for catching this regression.  Fix is in PR #186.   I will make a 1.2.1 release soon with this fix plus the fix for the regression reported in issue #182.
