### ISSUE TITLE
cftime._cftime.DatetimeGregorian incompatible with matplotlib

### ISSUE THREAD

**Issue by 5tefan** [Unidata/cftime#191]
- cftime version: 1.2.1
- python version: 3.7.0
- Issue: cftime._cftime.DatetimeGregorian incompatible with matplotlib

Minimal example:

```
import numpy as np
import cftime
import matplotlib.pyplot as plt

t = cftime.num2date(np.arange(10), "seconds since 2000-01-01 12:00:00")
plt.plot(t, np.arange(10))
```

Produces:
```
Traceback (most recent call last):
  File "cftime_example.py", line 6, in <module>
    plt.plot(t, np.arange(10))
  File "/opt/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2796, in plot
    is not None else {}), **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1667, in plot
    self.add_line(line)
  File "/opt/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 1902, in add_line
    self._update_line_limits(line)
  File "/opt/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 1924, in _update_line_limits
    path = line.get_path()
  File "/opt/anaconda3/lib/python3.7/site-packages/matplotlib/lines.py", line 1027, in get_path
    self.recache()
  File "/opt/anaconda3/lib/python3.7/site-packages/matplotlib/lines.py", line 670, in recache
    x = _to_unmasked_float_array(xconv).ravel()
  File "/opt/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 1390, in _to_unmasked_float_array
    return np.asarray(x, float)
  File "/opt/anaconda3/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'cftime._cftime.DatetimeGregorian'
```
Not sure if this is a cftime or a matplotlib issue. It would be nice if this worked out of the box. Ping  #136.

**Comment by jswhit** [comment]
We could support this if we knew what matplotlib was expecting from a datetime object.  I suggest bringing this up on the matplotlib issue tracker.

**Comment by jswhit** [comment]
Perhaps we could provide a custom converter that can be imported and registered by matplotlib (as pandas does, see https://matplotlib.org/3.1.1/faq/howto_faq.html)

**Comment by jswhit** [comment]
Actually, if a `toordinal` method is added to cftime.datetime, it looks like `matplotlib.dates.ConciseDateConverter` can be used to make this work.

```python
import numpy as np
import cftime
import matplotlib.pyplot as plt
import matplotlib.units as munits
from matplotlib.dates import ConciseDateConverter
munits.registry[cftime.DatetimeGregorian] = ConciseDateConverter()
t = cftime.num2date(np.arange(10), "seconds since 2000-01-01 12:00:00")
plt.plot(t, np.arange(10))
```

**Comment by spencerkclark** [comment]
[nc-time-axis](https://github.com/SciTools/nc-time-axis) handles this in a fairly robust way; it could be worth potentially seeing about merging the code there into cftime proper.  Note that you do not have to convert to their `CalendarDateTime` object anymore; you can plot cftime dates directly (see https://github.com/SciTools/nc-time-axis/pull/42).

**Comment by jswhit** [comment]
Wow - that's very nice!  However, bundling that with cftime would add a matplotlib dependency, which I don't think we want.

**Comment by spencerkclark** [comment]
I agree, we definitely don't want matplotlib as a required dependency.  There would probably be some way with try/except logic around the imports to make constructing and registering the converters optional, but it's for sure not an urgent need.  nc-time-axis is very simple to use and install as it is.

**Comment by jswhit** [comment]
closing now, since nc-time-axis seems to be the best solution.
