### ISSUE TITLE
strftime does not correctly format dates with year < 1000

### ISSUE THREAD

**Issue by aidanheerdegen** [Unidata/cftime#194]
* the version of the software with which you are encountering an issue

```
cftime: 1.2.1
```

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)

```
python: 3.7.2 (default, Dec 29 2018, 00:00:04) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
python-bits: 64
OS: Darwin
OS-release: 19.4.0
```

* a description of the issue with the steps needed to reproduce it

`cftime.strftime()` does not zero-pad years < 1000.
```python
In [1]: import datetime, cftime                                                                     
In [2]: datetime.datetime(year=1, month=1, day=1).strftime("%Y-%m-%dT%H:%M:%S")                     
Out[2]: '0001-01-01T00:00:00'
In [3]: cftime.datetime(year=1, month=1, day=1).strftime("%Y-%m-%dT%H:%M:%S")                       
Out[3]: '   1-01-01T00:00:00'
```

It seems that zero-padding years is platform dependent

https://bugs.python.org/issue13305

and on some systems `strftime/strptime` will not correctly round-trip. Trippy!

https://docs.python.org/dev/library/datetime.html#strftime-strptime-behavior

However, I don't see any platform that space pads years <1000 as `cftime` does. If `cftime` wants to have a fixed-width year I think it should be zero-padded

https://github.com/Unidata/cftime/blob/a5f5928d40c270e65d7928b6546dd20e60e808c2/cftime/_cftime.pyx#L1293

I do realise `isoformat()` exists and produces zero padded years correctly.

Related issue: https://github.com/pydata/xarray/issues/4337

**Comment by jswhit** [comment]
simple fix PR #195
