### ISSUE TITLE
Towards the first standalone release of netcdftime

### ISSUE THREAD

**Issue by jhamman** [Unidata/cftime#20]
My apologies for getting this started and then letting it slide for so long. I'd like to aim for getting a first release of this package by the end of February. 

I have created a milestone on the issue tracker for this release. Some other things to consider:

- what version number should we start with?
- how should we go about removing the current netcdftime from netcdf4-python

cc @dopplershift, @spencerkclark, @jswhit 

from @dopplershift:

> I'm happy to help step up on the infrastructure side (well, in a couple weeks probably), but I'm a little uncomfortable with stepping up fully since I don't have much technical knowledge in the space netcdftime is operating. So I'm happy to cut releases and stuff, but I'm not in possession of answers when it comes to solutions to problems.

If you could help get the documentation working, I can spend some cycles on getting the test infrastructure working again. I'm hoping @spencerkclark can help wrap up his open issues in that time frame.

**Comment by spencerkclark** [comment]
Thanks @jhamman and @dopplershift, that sounds great; indeed I would happy to help out in wrapping up my open issues.

**Comment by jswhit** [comment]
I can create a netcdf4-python branch with netcdftime removed.

**Comment by jswhit** [comment]
I created a 'nonetcdftime' branch in netcdf4-python.  I did not remove the utilities that use netcdftime, but they now will raise an ImportError it they are used and netcdftime is not installed.  I didn't remove the tests that use netcdftime either, but they are not run if netcdftime is not installed.

**Comment by jswhit** [comment]
I noticed that one of the tests is failing in master (test_parse_date_tz).  I think this is related to issue #17.  This needs to be fixed before the first standalone release.

**Comment by jhamman** [comment]
Folks, I think we're close here. Really, the only blocker to a release is the documentation. @dopplershift - do you think you'll be keen to help with that?

We probably also want a Appveyor CI test suite, so I just opened #21.

**Comment by dopplershift** [comment]
@jhamman Yeah, I just need to get in my scipy abstracts first, then I should be good to go.

**Comment by jhamman** [comment]
Alright, I think we are code complete for an initial release. I'd like to issue a alpha release so we can setup conda-forge and pypi. That will give @dopplershift time to jump in on the documentation stuff.

Any objections to tagging `v0.1.0a1`?

**Comment by shoyer** [comment]
It might actually make sense to start with a 1.0 release. netcdftime is pretty mature from it's development inside netCDF4-Python.

**Comment by dopplershift** [comment]
I guess the real question is: is anyone intending to break the existing interfaces?

**Comment by jhamman** [comment]
1.0 is fine by me. Any objections? If not, I'll probably make a `v1.0.0a1` tag later today.

**Comment by jhamman** [comment]
> I guess the real question is: is anyone intending to break the existing interfaces?

Not that I'm aware of. The main motivation for this split is to drop the dependency of netcdf. My vision, at least in the short term, is for the API to remain as is.

**Comment by dopplershift** [comment]
Then I’d say 1.0 is fine.

**Comment by jhamman** [comment]
alpha tag has been made: https://github.com/Unidata/netcdftime/releases/tag/v1.0.0a1

pypi upload: https://pypi.org/project/netcdftime/

conda-forge staged recipe: https://github.com/conda-forge/staged-recipes/pull/5189

**Comment by dopplershift** [comment]
@jswhit Is there any source material for the `docs/index.html` file in the netCDF4 repo?

**Comment by jhamman** [comment]
I'm going to make a second release candidate tag.

**Comment by jhamman** [comment]
anyone opposed to making another cftime tag?

**Comment by spencerkclark** [comment]
@jhamman I'm biased, but I say go for it.  I have some commits that finish up pydata/xarray#1252 that I'll wait to push until the latest `cftime` is up on conda-forge.  Thanks again for your help pushing this forward.

**Comment by jswhit** [comment]
netcdf4-python 1.4.0 is released, the first release that depends on the unbundled cftime.

**Comment by jhamman** [comment]
Thanks @jswhit - let's try to get a full release of cftime out next week.
