### ISSUE TITLE
Missing v1.3.0rel tag/release

### ISSUE THREAD

**Issue by ArchangeGabriel** [Unidata/cftime#214]
The release is advertised in the [changelog](https://github.com/Unidata/cftime/blob/master/Changelog) but is not present under either [releases](https://github.com/Unidata/cftime/releases) nor [tags](https://github.com/Unidata/cftime/tags).

**Comment by ArchangeGabriel** [comment]
Wow, cannot believe how synchronized we where (I had the update to 1.3.0 on my todo list since November 20th)… I’ve received the notification email for the release exactly after clicking “Comment”.

That being said, the release was now tagged with a changelog file mentionning the 1.3.1 release and the corresponding #212 PR that is indeed included. Is that expected?

**Comment by jswhit** [comment]
fixed now

**Comment by ArchangeGabriel** [comment]
Does not seems so, e.g. https://github.com/Unidata/cftime/blob/v1.3.0rel/cftime/_cftime.pyx#L56 this does not look right to me: the v1.3.0rel tag is pointing to a state that is 1.3.1 (also in the changelog).

**Comment by jswhit** [comment]
sorry, it's really fixed now.
