### ISSUE TITLE
no v1.3.1 wheel for win32 py36

### ISSUE THREAD

**Issue by amoodie** [Unidata/cftime#224]
No wheel for Windows 32 bit in latest release? Build error?

Not an issue with `cftime`, but I think with the release from 1.3.1 yesterday. I'm getting a "no wheel available" error for a windows 32bit python 3.6 build here: https://github.com/DeltaRCM/pyDeltaRCM/pull/127/checks?check_run_id=1724457953#step:4:138

Looking at the released files on pypi (https://pypi.org/project/cftime/#files) it appears no wheel was built for the described system, whereas win32 wheels were built for v1.3.1 for py37, py38, and py39. Moreover, v1.3.0 had a release for win32 py36.

Not sure if this was intentional or not, so I figured I'd report it. Is py36 at end-of-life? 

Cheers, AM

**Comment by jswhit** [comment]
Windows wheels are provided by @cgohlke  (https://www.lfd.uci.edu/~gohlke/pythonlibs/), and he hasn't yet build a wheel for 3.6.  Don't know if he plans to provide one - if not, you're stuck at 1.3.0 on windows.

**Comment by amoodie** [comment]
okay, no worries. I thought they were built automatically on release by one of the Actions workflows on the repo. I'll wait and see what comes down. Feel free to close.

**Comment by jswhit** [comment]
the github actions workflow for [cftime-wheels](https://github.com/MacPython/cftime-wheels) only builds macos and linux wheels.  It would be great if someone were willing to contribute a windows wheel building workflow.

**Comment by johannes-mueller** [comment]
This issue just made the build pipeline of my project fail. Not actually sure why, as on my local windows machine I can `pip install cftime` in a 3.6 venv just fine. The wheel builds smoothly, I am not sure why my build pipeline on GitHub fails. Anyway I would really be glad to have a cp36-win wheel available for the current cftime versions.

I don't know if it helps as I don't know anything about the cftime codebase and its dependencies, but feel free to take a look at my wheel building workflow which builds wheels for Linux and Windows.

https://github.com/boschresearch/pylife/blob/develop/.github/workflows/pypi-deploy.yml

It is based on https://github.com/joerick/cibuildwheel which might be worth a look. They say, that they also build wheels for macos.

**Comment by jswhit** [comment]
1.3.1 py36 windows wheels now available on pypi, thanks to @cgohlke
