### ISSUE TITLE
comparing vs. subtracting different calendars

### ISSUE THREAD

**Issue by mathause** [Unidata/cftime#236]
The following snipped used to raise a `TypeError`. With the changed behavior of `__richcompare__` this now raises a `ValueError` in `__sub__` which pandas ignores:

```python
import pandas as pd
import cftime

time_1 = cftime.DatetimeGregorian(2000, 1, 1)
time_2 = cftime.DatetimeProlepticGregorian(2001, 1, 1)

pd.Series([time_1, time_2]).rank(method="dense", numeric_only=False)
```

This [is used in xarray](https://github.com/pydata/xarray/blob/643e89ee7201e8bc730dcde19c3dc1c34fbd1ed5/xarray/core/combine.py#L96) to avoid combining datasets with different calendars, which does not really work anymore with this change. I don't know why pandas ignores the error (and it's not silent). So it's not really a cftime issue but I thought I report it here anyway.

- Do you plan to allow `__sub__` between different calendars?
- Should `__sub__` raise a `TypeError` instead of a `ValueError`

**Comment by jswhit** [comment]
PR #234 enabled __richcmp__ between different calendars.  You are right that the error should be changed to a TypeError. I will create a PR for that.    As far as enabling __sub__ and __add__ between different calendars, that's a tricky one.  It's possible, but which calendar type would be returned?  PR #234 also added a `change_calendar` method that can be used to achieve this - I think it's probably better to force users to explicity do `d1 + d2.change_calendar(d1.calendar)`.

**Comment by jswhit** [comment]
PR #236 merged.  @mathause please let us know whether that fixes the xarray tests

**Comment by spencerkclark** [comment]
Great, thanks @jswhit -- that indeed fixed the issue @mathause identified.  The removal of `utime` (https://github.com/Unidata/cftime/pull/235) resulted in some nc-time-axis-related test failures in xarray as well (it appears nc-time-axis makes extensive use of it).  

It was fairly straightforward to remove nc-time-axis's use of `utime` (see my updates to https://github.com/jswhit/nc-time-axis/pull/1).  Do you think we should try and get https://github.com/SciTools/nc-time-axis/pull/51 merged there?  It sounds like they would make a new release after that: https://github.com/SciTools/nc-time-axis/issues/54#issuecomment-776755196.

**Comment by mathause** [comment]
Unfortunately it did not work. Actually pandas ignores the `TypeError` silently :facepalm: 

https://github.com/pandas-dev/pandas/blob/029907c9d69a0260401b78a016a6c4515d8f1c40/pandas/_libs/algos.pyx#L87

Still I think `TypeError` is the right one to raise - so I guess we have to fix this in xarray & am not sure how to best do this. Pity, the old version was quite elegant.

**Comment by spencerkclark** [comment]
Oops, I don't know how I missed that that test still failed in the xarray test suite...thanks @mathause for correcting me.

**Comment by mathause** [comment]
I think from my side this can be closed - thanks @jswhit & @spencerkclark
