### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [Unidata/cftime#243]
Problem
---------
On aarch64, ‘pip install cftime’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some more time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install cftime’ should download the wheels from pypi

@jswhit Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by jswhit** [comment]
The wheel building repo is at http://github.com/MacPython/cftime-wheels.  It uses github actions (yaml in .github/workflows/build-windows-wheels.yml) to build ManyLinux wheels using multibuild.  Feel free to create a PR there to add support for building aarch64 wheels.

**Comment by jswhit** [comment]
It also builds macos x wheels - is this the architecture for the new M1 macs?

**Comment by odidev** [comment]
I have raised the PR to build the wheel for linux aarch64 using multibuild.
**PR Link** - https://github.com/MacPython/cftime-wheels/pull/6

**Comment by jswhit** [comment]
MacPython/cftime-wheels#6 was merged and aarch64 wheels are now up on pypi.
