### ISSUE TITLE
Implement matplotlib converters?

### ISSUE THREAD

**Issue by aulemahal** [Unidata/cftime#247]
Since the 1.5.0 release, plotting cftimes with matplotlib is broken because `nc-time-axis` uses deprecated parts of cftime. A PR was open to fix this issue (SciTools/nc-time-axis#59), but it hasn't seen any activity yet. In fact, that package is not very active in general (which is understandable as it is quite small). 

I was wondering if it would make sense to implement its functionality directly here, in `cftime`?  Matplotlib would not be added as a dependency, but when present the converters could be registered upon import? The code seems low maintenance in general and with a compatible licence, but moving it here would reduce the number situations like right now.

I am willing to contribute to this. 

What do @jbusecke, @trexfeathers and @jswhit think?

**Comment by jswhit** [comment]
I know nothing about how nc-time-axis works either.  If it's a simple matter of converting to a matplotlib standard calendar, we could provide that here - but providing tickers and formatters should be left in a separate package I think.  Seems like the fundamental problem is that nc-time-axis is not very actively maintained.

**Comment by trexfeathers** [comment]
>Seems like the fundamental problem is that nc-time-axis is not very actively maintained.

I agree. We create many good ideas in the SciTools organisation without knowing if we have the resource/priority to maintain them. I will continue to keep my colleagues up to date on these problems, so we can try to find time to sort them out.

**Comment by aulemahal** [comment]
@jswhit Sadly, I don't think converting to a standard calendar would work as expected, all those non-standard dates would get in the way. The `nc-time-axis` package is pretty much 3 classes : a Ticker, a Locator and a Converter. The latter converts to integers (rather than to standard datetimes). 

I believe it is not actively maintained in part because it is relatively low maintenance : the matplotlib interface seems quite stable.

**Comment by jswhit** [comment]
@aulemahal so you are proposing moving the Converter from nc-time-axis here (without adding a matplotlib dependency)?   From a cursory look at the code it seems that it won't be that simple (the Converter uses the Locator and the Formatter).

**Comment by aulemahal** [comment]
Oh no, sorry. previous comment was a bit ambiguous. 
I am suggesting moving the whole thing to cftime. Without adding a matplotlib dependency indeed. Idea: put this in a "mpl_utils.py"  and, in `__init__.py` do:

```python
try: 
    import matplotlib
except ImportError:
    pass
else:
    import mpl_utils
```

**Comment by trexfeathers** [comment]
>@trexfeathers what do you think?

I'm going to spend some time this week trying to sort out nc-time-axis, cf-units, and any other dependent packages we have that are struggling to keep pace.

**Comment by bjlittle** [comment]
Ping @aulemahal 

Fancy joining the discussion over on [SciTools/nc-time-axis](https://github.com/SciTools/nc-time-axis/discussions/60) ? :smile:

**Comment by jswhit** [comment]
sounds like nc-time-axis is getting jumpstarted - which means we shouldn't throw a monkey wrench in that effort by merging nc-time-axis functionality into cftime.  Going to close this now.
