### ISSUE TITLE
Calendar-specific datetime subclasses lose their identity after pickling

### ISSUE THREAD

**Issue by spencerkclark** [Unidata/cftime#251]
After pickling it appears that calendar-specific subclasses of `cftime.datetime` objects lose their identity.  This causes integration issues between downstream libraries that depend on serialization, e.g. between `xarray` and `distributed` (pydata/xarray#5686).  

Minimal working example:
```
>>> import cftime; import pickle
>>> serialized = pickle.dumps(cftime.DatetimeNoLeap(2000, 1, 1))
>>> deserialized = pickle.loads(serialized)
>>> deserialized
cftime.datetime(2000, 1, 1, 0, 0, 0, 0, calendar='noleap', has_year_zero=True)
```
I would expect `deserialized` to retain its `cftime.DatetimeNoLeap` type.  Is there a way to make sure that the type is round-tripped through pickling?

cc: @aidanheerdegen

**Comment by jswhit** [comment]
The serialization happens through the `__reduce__` method

```python
    def __reduce__(self):
        """special method that allows instance to be pickled"""
        args, kwargs = self._getstate()
        return (_create_datetime, (args, kwargs))
```
I suppose we could support serialization of datetime specific instances with a bunch if if-statements here, but on the other hand I thought datetime specfic instances were deprecated anyway (since downstream libs can just check the `calendar` instance variable instead).

**Comment by spencerkclark** [comment]
Thanks @jswhit -- I sort of answered my own question -- I have a solution in #252.  We have not yet fully adopted the universal `cftime.datetime` in xarray, so we still use the subclasses internally (this was motivation for the 1.4.1 release which restored those for the time being).

**Comment by jswhit** [comment]
That's a very nice solution @spencerkclark

**Comment by jswhit** [comment]
closed by PR #252

**Comment by aidanheerdegen** [comment]
Thanks for the prompt fix.

Do you have a timeline for the next release? This bug prevents currently used code from working correctly, but we're relying on `>1.5` for the latest `xarray` release I believe.

**Comment by aidanheerdegen** [comment]
Sorry to be a pain @jswhit, but this bug is affecting users, so any update on when `1.5.1` will be released?
