### ISSUE TITLE
Feature request: Make a public property for is_leap

### ISSUE THREAD

**Issue by bzah** [Unidata/cftime#259]
cftime version: 1.5.1.1
xarray version: 0.19.0

---
In Xarray, using `CFTimeIndex` it is now possible to mimic the behavior of pandas `dt` accessor but only for some properties of CfTime.
I saw that `_is_leap` already exist in cftime [here](https://github.com/Unidata/cftime/blob/a47efb5804f67aa1595c30a56c8f007db0c0d224/src/cftime/_cftime.pyx#L1727).

Would it be possible to make a public property `is_leap` to mimic `da.time.dt.is_leap_year`  ?

_I can push a PR if it's approved._

**Comment by jswhit** [comment]
It's possible, but I don't want to add all the methods of Pandas.Series.dt to cftime.datetime (monthname, quarter, weekday etc) so I guess I'd rather not start down that road.

**Comment by jswhit** [comment]
PR #260 makes a public `cftime.is_leap_year` function.

**Comment by jswhit** [comment]
PR #260 merged, closing now...
