### ISSUE TITLE
Support time units that are a multiple of second, hour, or day (with a reference date)

### ISSUE THREAD

**Issue by ckhroulev** [Unidata/cftime#300]
`cftime` does not support units similar to "10days since 2000-1-1" even though this unit string is valid according to the [UDUNITS2 unit grammar](https://www.unidata.ucar.edu/software/udunits/udunits-2.2.28/udunits2lib.html#Grammar) and is not ambiguous (unlike "year since 2000-1-1").

Note: I understand the reason why "year since YYYY-MM-DD" is disallowed and agree with that decision.

The minimal example
``` python
time_units = "10days since 2000-1-1"
calendar="365_day"

import cftime
import cfunits
import sys

print(f"Python version: {sys.version}")
print(f"cftime version: {cftime.__version__}")
print(f"cfunits version: {cfunits.__version__}")

print(cfunits.Units(time_units, calendar).reason_notvalid)

try:
    cftime._dateparse(time_units, calendar)
except ValueError as e:
    print(e)
```
produces the following
```
Python version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
cftime version: 1.5.2
cfunits version: 3.3.5
units must be one of 'seconds', 'minutes', 'hours' or 'days' (or singular version of these), got '10days'
units must be one of 'seconds', 'minutes', 'hours' or 'days' (or singular version of these), got '10days'
```
As you can see from this example, this behavior breaks [cfunits](https://ncas-cms.github.io/cfunits/index.html).

Moreover, this also breaks [cfchecker](https://github.com/cedadev/cf-checker) (which uses `cfunits`): files containing some valid and unambiguous time units are considered non-compliant.

Thanks for your time!

**Comment by jswhit** [comment]
Let me make sure I understand - a unit of '5days' should be equivalent to a pentad?  I've never seen that before.

**Comment by ckhroulev** [comment]
@jswhit `5days` is equivalent to `5 * 86400 * second`. This is nothing new; for example, [`week` is defined as `7 day`](https://github.com/Unidata/UDUNITS-2/blob/c83da987387db1174cd2266b73dd5dd556f4476b/lib/udunits2-common.xml#L1026-L1030), `day` is defined as `24 h`, `h` as  `60 min`, and `min` is `60 s`.

**Comment by jswhit** [comment]
OK, but it's non-trivial to make this work for any arbitrary integer. I don't think we can support this unless someone volunteers to do it.

**Comment by jswhit** [comment]
Looking at https://ncics.org/portfolio/other-resources/udunits2/, there are other examples of time units allowed by udunits that cftime will choke on, like `sidereal_year'. and 'jiffy'.  CF  [time units](https://cfconventions.org/cf-conventions/cf-conventions.html#time-coordinate) conventions seem to suggest that all supported time units are OK, but this seems to me to be unrealistic.

**Comment by ckhroulev** [comment]
Hmm. A more careful reading of [Section 3.1 Units of the CF document](http://cfconventions.org/cf-conventions/cf-conventions.html#units) tells me that I'm wrong to assume that `10 days` is valid:
> The UDUNITS syntax that allows scale factors and offsets to be applied to a unit is not supported by this standard, except for case of specifying reference time [...]

(`... since YYYY-MM-DD` is an "offset" in that lingo).

> Do we know of any real-world use cases of units like `10days since`?

I've been using `365days since YYYY-MM-DD` in [PISM](https://pism.io) to make it abundantly clear that we mean 365-day years, but I should just switch to `common_year`.

So, I think this issue should be closed. Thanks for looking into this!
