### ISSUE TITLE
DOC: How to install netcdftime

### ISSUE THREAD

**Issue by jhamman** [Unidata/cftime#31]
We need to document that netcdftime is available on pypi and conda-forge. Probably also how to build from source.

**Comment by jswhit** [comment]
ideally, we should provide binary wheels also (since those are available for netcdf4-python, which now won't include netcdftime in version 1.3.2)

**Comment by jhamman** [comment]
@jswhit - how are the netcdf4 wheels built?

**Comment by jswhit** [comment]
@cgohlke builds the windows ones (https://www.lfd.uci.edu/~gohlke/pythonlibs/) and @matthew-brett builds the linux and mac ones (https://github.com/MacPython/netcdf4-python-wheels) using travis.  I suppose appveyor could be used to build the windows wheels.

**Comment by ocefpaf** [comment]
I can work on that today @jhamman.
