### ISSUE TITLE
reformat axis, calendar, units or all? Repeating time ranges

### ISSUE THREAD

**Issue by kaos000** [Unidata/cftime#314]
Hi, I am fumbling my way through working with NetCDF files in R and have a large palaeoclimate.nc that has this time dimension: 
  time  Size:11500   *** is unlimited *** 
            standard_name: time
            units: hours since 1-1-1 00:00:00
            calendar: standard
            axis: T

The thing is, I would like to reformat the time units so they properly reflect BP. I assume I have to change the calendar as well. 
Right now, the range of time is only 1000 years, so the hours since 1-1-1 00:00:00 reset for each 1000-year span, making it difficult to create a time series. 
Is there a straightforward way to accomplish this? Or do I need the author of the file to recode it?
Thanks!
K

_Originally posted by @kaos000 in https://github.com/Unidata/cftime/issues/234#issuecomment-1864334700_

**Comment by jswhit** [comment]
Not sure what you mean by 'reformat the time units', but I if you mean change the time units and update the time values consistently you will have to rewrite the dataset.  This should be fairly straightforward - just make a copy of the Dataset, open in 'append' mode, change the time units and write new time values.
