### ISSUE TITLE
No `aarch64` wheels on PyPI

### ISSUE THREAD

**Issue by hoechenberger** [Unidata/cftime#333]
Hello, following #243, I expected to find `aarch64` wheels on PyPI. However, at least for the latest release, there are none. Is this intentional? Could you please provide binaries for `aarch64`? Thank you!

**Comment by jswhit** [comment]
When we switched to cibuildwheel from multibuild the aarch64 support got left behind. @ocefpaf could you have a look at adding this when you have time?

**Comment by hoechenberger** [comment]
That would be amazing, thank you very much for looking into this! Background is that I'm running Docker on Apple Silicon -- something that's becoming more and more widespread.

FWIW @larsoner has gathered quite some experience with aarch64 builds on CI systems over the past week or so; I'm sure he'd gladly lend you a hand if need be!

(Just handing out @larsoner's time like it's candy without asking him first ... 😅😅😅😅😅)

**Comment by larsoner** [comment]
Opened https://github.com/Unidata/cftime/pull/334
