### ISSUE TITLE
sdist not uploaded to pypi by github action

### ISSUE THREAD

**Issue by jswhit** [Unidata/cftime#339]
[publish.yml](https://github.com/Unidata/cftime/blob/master/.github/workflows/publish.yml) does not upload a source distribution, only wheels

**Comment by ocefpaf** [comment]
That one should be removed. Probably an oversight on my part.  Everything, wheels and sdist, is built in the cibuildwheel.yml file now.

https://github.com/Unidata/cftime/blob/9ec687ba37612bd12f9b736a6febba57d3b8bd41/.github/workflows/cibuildwheel.yml#L81

It should be an easy PR. I'll send it in a moment.
