### ISSUE TITLE
netcdftime cannot be used with netCDF4-python<=1.3.1

### ISSUE THREAD

**Issue by mcgibbon** [Unidata/cftime#36]
As discussed in #32, when netCDF4 is installed its version of netcdftime overrides any installation of this package. It is very difficult to expect scientific python users to have the most up to date version of netCDF4, so up to date that it does not exist yet. This gives very strange behavior that is difficult to debug unless you've already run into it.

There is a really simple fix for this, which is to rename the netcdftime package, or provide an alias package name. This would remove a massive package incompatibility problem.

At the very least, netcdftime should require that these older versions of netCDF4 are *not* installed. This would allow me to tell users that they need to install netcdftime to get X functionality, and have a guarantee that when they do so they will not run into these import problems. One way to do this would be to check in netCDF4 whether netCDF4 is installed, and if it is installed to add a dependency on netCDF4 having at least the required version.

**Comment by dopplershift** [comment]
Problem is that `setup.py` is not executed for wheels, so there's nothing that can be done except declaring a dependency on an unreleased netcdf4-python, which would then *require* it (the unreleased version). That sounds bad.

Another option would be to look for it at run time and issue a warning...that still feels dirty to me, though.

**Comment by mcgibbon** [comment]
I mean, the issue is large enough for me that I'd consider forking this package for the sole purpose of changing the package name. But that doesn't seem like a good solution.

In essence, this package has a name conflict with another package (netCDF4), and should probably not have been named netcdftime to begin with because of that conflict. As of present (without the unreleased netCDF4 version), the conflict is just as bad as if this package were named `netCDF4`. And in practice for users with outdated python installations installed through system package managers, it may remain that bad for a long time.

**Comment by jswhit** [comment]
+1 for a name change - seems like the least painful solution to me

**Comment by jhamman** [comment]
Fine by me. How about `cftime`?

**Comment by mcgibbon** [comment]
`cftime` sounds very reasonable.

**Comment by dopplershift** [comment]
To me as well.

**Comment by jhamman** [comment]
okay, let's plan on making this change asap. @mcgibbon - can you make a PR here? 

I think I can manage the xarray/pypi/conda-forge changes.

**Comment by mcgibbon** [comment]
PR #38 made. The way I wrote it requires the github repo and pypi name be changed to `cftime`, and any appveyor/travis/conda configuration that needs to be changed as a result.

**Comment by jhamman** [comment]
I've made a new alpha tag and setup pypi with this release. Conda-forge is being built now.
