### ISSUE TITLE
datetime.timetuple returns a tuple, not a time.timetuple

### ISSUE THREAD

**Issue by mcgibbon** [Unidata/cftime#43]
Unlike the built-in `datetime`, `cftime.datetime.timetuple()` returns a `tuple` and not a `time.timetuple`. I'll submit a PR to correct this.

**Comment by jswhit** [comment]
@mcgibbon - have you had any time to work on this?

**Comment by mcgibbon** [comment]
@jswhit The PR was completed and merged, so this issue is resolved.
