### ISSUE TITLE
cftime not on pypi for Python 2.7?

### ISSUE THREAD

**Issue by mcgibbon** [Unidata/cftime#45]
In a Travis build running `pip install cftime` ([line 458](https://travis-ci.org/mcgibbon/sympl/jobs/373211185)), the command is failing with a message that indicates there is no cftime available for Python 2.7. This seems wrong to me since there is a [source distribution available on pypi](https://pypi.org/project/cftime/#files). Is this a problem on your end or on mine, and any ideas what the cause may be?

**Comment by jhamman** [comment]
No ideas from me. Can you use conda-forge? We have discussed setting up a continuous deployment to build windows wheels but we haven't gotten there yet.

**Comment by mcgibbon** [comment]
I can't use conda-forge in Travis. In theory I can, but when I originally tried to set it up using conda it was very difficult to do so and I gave up. I'd rather not completely re-configure travis when pip should work. Unless there's a way to use conda-forge through pip, or install conda through pypi.

**Comment by mcgibbon** [comment]
I think my actual problem is due to `pyopenssl 17.5.0 has requirement cryptography>=2.1.4, but you'll have cryptography 1.4 which is incompatible.`, as I can install cftime through pip on another machine. Closing.
