### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by ocefpaf** [Unidata/cftime#46]
`netcdf4` version 1.4.0 uses `cftime` and it will be released soon on PyPI. (It is already [available on GitHub](https://github.com/Unidata/netcdf4-python/releases/tag/v1.4.0rel) and conda-forge is shipping it.)

It would be nice if we could have a stable release of `cftime` to accompany `netcdf4 1.4.0`.

**Comment by jhamman** [comment]
Yes, I think we're ready for this. I'd like to get some doc related issues tied up. If someone has time to take care of #31, I think that plus #44 should be all we need to get the final release done.

**Comment by jhamman** [comment]
release is up on pypi and github. conda-forge is pending tests/builds.
