### ISSUE TITLE
num2date returns 01:00:00 or 00:59:59 depending on calendar

### ISSUE THREAD

**Issue by demorym** [Unidata/cftime#54]
Good afternoon,

Here is an issue I posted on https://github.com/Unidata/netcdf4-python/issues/810 two weeks ago, and I have been advised to submit it here. Here it is below:

You may already be aware of this problem, but I didn't find how to solve it.
I have an output with hourly intervals written in days since 1979-01-01 00:00:00.
The first time step is 0. The second is 0.041666666667.
I have noticed that num2date does not give the same results when reading the second time step depending on the calendar used. It sometimes give 1979-01-01 01:00:00 (which is what we want), and sometimes 1979-01-01 00:59:59 (see below).
How can we fix it so num2date would give the correct result (01:00:00. 02:00:00, etc.) whatever calendar is used?

Thank you for your help,
Marie-Estelle

time_in1=0.041666666667
print(time_in_units)
days since 1979-01-01 00:00:00
dt_in1 = num2date(time_in1,time_in_units,calendar='standard')
str(dt_in1)
'1979-01-01 01:00:00'
dt_in1 = num2date(time_in1,time_in_units,calendar='gregorian')
str(dt_in1)
'1979-01-01 01:00:00'
dt_in1 = num2date(time_in1,time_in_units,calendar='proleptic_gregorian')
str(dt_in1)
'1979-01-01 01:00:00'
dt_in1 = num2date(time_in1,time_in_units,calendar='noleap')
str(dt_in1)
'1979-01-01 00:59:59'
dt_in1 = num2date(time_in1,time_in_units,calendar='365_day')
str(dt_in1)
'1979-01-01 00:59:59'
dt_in1 = num2date(time_in1,time_in_units,calendar='360_day')
str(dt_in1)
'1979-01-01 00:59:59'
dt_in1 = num2date(time_in1,time_in_units,calendar='julian')
str(dt_in1)
'1979-01-01 01:00:00'
dt_in1 = num2date(time_in1,time_in_units,calendar='all_leap')
str(dt_in1)
'1979-01-01 00:59:59'
dt_in1 = num2date(time_in1,time_in_units,calendar='366_day')
str(dt_in1)
'1979-01-01 00:59:59'

**Comment by demorym** [comment]
Do you know how I could go around this?

**Comment by jswhit** [comment]
No, not without a rewrite of our julian day arithmetic to preserve more precision.

**Comment by jswhit** [comment]
Don't know whether this helps, but if you know the precision is 1 hour, you can do

    print d.strftime(format="%Y-%m-%d %H")

**Comment by jswhit** [comment]
Adding a small offset to the time seems to do it, i.e.

    >> d = cftime.num2date((1./24.)+1.e-6,'days since 1979-01-01 00:00:00',calendar='365_day')
    >> print d

    1979-01-01 01:00:00

**Comment by demorym** [comment]
It works indeed. Thank you so much for your help!
