### ISSUE TITLE
Building with icc failes

### ISSUE THREAD

**Issue by dschwoerer** [Unidata/cftime#56]
I have been trying to build with `icc`, but that failes as for the linking of the so, `gcc` is used instead.

Other extensions seem to work fine.
You can reproduce this issue as well without an extra compiler:

```
CC=echo CXX=echo python3 setup.py build_ext
```

I have tested other extensions, and they use echo for compiling and linking, whereas cftime uses it only for compiling, and gcc for linking.

This issue is present in master, as well as cftime-1.0.0 from pypi.

**Comment by dopplershift** [comment]
Can you point to one that works with your `echo` test? Looking over the `setup.py`, I don't see anything that looks wrong. It seems to just be using `setuptools`.

**Comment by dschwoerer** [comment]
I thought it would be working for netcdf4-python, but that came apparently pre-compiled :-/

It is working for me in boutcore:
https://github.com/boutproject/BOUT-dev/blob/next/tools/pylib/_boutcore_build/setup.py.in

**Comment by dschwoerer** [comment]
I noticed boutcore is using `distutils.core` rather then `setuptools`
I guess I should report this to setuptools ...

**Comment by jswhit** [comment]
LDSHARED needs to be set to change the linker from gcc to icc.

**Comment by dschwoerer** [comment]
Thanks, setting LDSHARED resolves the issue.
Would really be nice if that would be documented ...
