### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by rabernat** [Unidata/cftime#85]
There have been 134 commits since the release of cftime 1.0.0 in May.

Give the large number of recent bugfixes and feature additions, perhaps a new release soon would be appropriate?

Thanks to everyone who works on this important package.

**Comment by rabernat** [comment]
My mistake, I had been looking at the releases page, not the tags page:
https://github.com/Unidata/cftime/tags

**Comment by jswhit** [comment]
I think I new release is warranted - I'll try to get 1.0.3 out this weekend.

Still would be nice to have a way to build binary wheels though (see issue #84)

**Comment by jhamman** [comment]
my 2 cents - I don't think we need to hold up releases for binary wheels. We need someone who cares about wheels for cftime and knows how to automate the deployment of them to engage here. It doesn't sound like we have that person at the moment so I suggest we proceed in the interim with releases as normal.

**Comment by jswhit** [comment]
conda is failing in the appveyor tests (pull request #86).  This is blocking the release.  @ocefpaf or @bjlittle, do either of you have any idea how to fix this?

**Comment by jswhit** [comment]
OK, now it's working - must have been an appveyor glitch.
