### ISSUE TITLE
1.0.3 fails to build on 32bit architectures due to test failures (TypeError: object of type 'numpy.int32' has no len())

### ISSUE THREAD

**Issue by sebastic** [Unidata/cftime#93]
The Debian package build for cftime 1.0.3 failed on 32bit architectures due to test failures, see:

 https://buildd.debian.org/status/package.php?p=cftime

The buildlog contains many `TypeError` issues like this:
```
=================================== FAILURES ===================================
____________________________ cftimeTestCase.runTest ____________________________

self = <test_cftime.cftimeTestCase testMethod=runTest>

    def runTest(self):
        """testing cftime"""
        # test mixed julian/gregorian calendar
        # check attributes.
        self.assertTrue(self.cdftime_mixed.units == 'hours')
        self.assertTrue(
            str(self.cdftime_mixed.origin) == '0001-01-01 00:00:00')
        self.assertTrue(
            self.cdftime_mixed.unit_string == 'hours since 0001-01-01 00:00:00')
        self.assertTrue(self.cdftime_mixed.calendar == 'standard')
        # check date2num method. (date before switch)
        d = datetime(1582, 10, 4, 23)
        t1 = self.cdftime_mixed.date2num(d)
        assert_almost_equal(t1, 13865687.0)
        # check num2date method.
>       d2 = self.cdftime_mixed.num2date(t1)

test/test_cftime.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cftime/_cftime.pyx:874: in cftime._cftime.utime.num2date
    ???
cftime/_cftime.pyx:492: in cftime._cftime.DateFromJulianDay
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TypeError: object of type 'numpy.int32' has no len()
```

Full buildlogs for the achitectures in question: [armel](https://buildd.debian.org/status/fetch.php?pkg=cftime&arch=armel&ver=1.0.3-1&stamp=1543749866&raw=0), [armhf](https://buildd.debian.org/status/fetch.php?pkg=cftime&arch=armhf&ver=1.0.3-1&stamp=1543750107&raw=0), [i386](https://buildd.debian.org/status/fetch.php?pkg=cftime&arch=i386&ver=1.0.3-1&stamp=1543749425&raw=0), [mips](https://buildd.debian.org/status/fetch.php?pkg=cftime&arch=mips&ver=1.0.3-1&stamp=1543751084&raw=0), [mipsel](https://buildd.debian.org/status/fetch.php?pkg=cftime&arch=mipsel&ver=1.0.3-1&stamp=1543754514&raw=0), [hppa](https://buildd.debian.org/status/fetch.php?pkg=cftime&arch=hppa&ver=1.0.3-1&stamp=1543751829&raw=0), [hurd-i386](https://buildd.debian.org/status/fetch.php?pkg=cftime&arch=hurd-i386&ver=1.0.3-1&stamp=1543756729&raw=0)

**Comment by jswhit** [comment]
I think pull request #94 ought to fix it.  I can make a new release with this fix (1.0.3.1) if need be.

**Comment by sebastic** [comment]
> What version of cftime did you have your last successful build against?

1.0.2.1, see the buildd history:

 https://buildd.debian.org/status/logs.php?pkg=cftime&ver=1.0.2.1-1&suite=sid

**Comment by jswhit** [comment]
BTW: pull request #94 is available in branch `issue93`

**Comment by sebastic** [comment]
The changes from #94 fix the build failure on i386 at least.

I've added the changes as patch to the Debian package, and uploaded the new revision to see if it also fixes the issue on the other architectures (which is to be expected).

**Comment by jswhit** [comment]
Great - thanks for the report

**Comment by sebastic** [comment]
Confirmed fixed on the arm* & mips* too.
